// convert file to a Byte Array
// with Files.readAllBytes() method
// https://www.geeksforgeeks.org/java-program-to-convert-file-to-a-byte-array/

// import classes
import java.io.*;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;

// main class
public class F2BA {

    // main driver method
    public static void main (String[] args)
        throws IOException
    {
        // create Path class object and assign local dir of file to it
        Path path = Paths.get("E:\\2_DEV\\DEV_coding\\test\\text.txt");

        // convert file into Byte Array
        byte[] arr = Files.readAllBytes(path);

        // print generated Byte Array
        System.out.println(Arrays.toString(arr));
    }
}

// javac F2BA.java
// java F2BA
